### ISSUE TITLE
Cambridge 20/21 | Concurrent and Distributed Systems (partIB)

### ISSUE THREAD

**Issue by vycezhong** [vycezhong/cs-notes#1]
https://www.youtube.com/playlist?list=PLeKd45zvjcDFUEv_ohr_HdUFe97RItdiB

notes: https://www.cl.cam.ac.uk/teaching/2021/ConcDisSys/dist-sys-notes.pdf

讲课的是DDIA作者Martin Kleppmann. 太赞了. 

话说英国口音真好听（逃

**Comment by vycezhong** [comment]
## Lecture 1
主要是回顾network基础

- latency: 消息传递所需要的时间
- bandwidth: 单位时间传输数据量

RPC:
![image](https://user-images.githubusercontent.com/25879526/115554834-79383480-a2e1-11eb-9095-00d8fb504047.png)
中间那个序列化过程叫做marshal / unmarshal, 做这件事的叫stub. 

REST居然也是rpc, 消息走的是json. 

microservices之间一般通过rpc通信. 

interface definition language(IDL): 语言独立的API specification. 比如protobuf.

**Comment by vycezhong** [comment]
## Lecture 2: Models of distributed systems

### 两军问题

由于信道不可靠，导致两个人无法达成共识.

比如A发消息给B，有两种情况
1. B收到了，但是ack消息挂了.
2. B没收到. 

这两种情况对于A来看是一样的——都是no response. 但是对于B来讲又是两件事. 

A有两个选择:
1. 一定attack: 多次发送相同消息. 只要有一个消息成功那就成功了. 但仍有可能失败.
2. 只有收到ack才attack: 但这样B就处于和A相同的境地了. 因为B不知道ack消息A是否收到. 这样会无限死循环下去. （猜疑链）

这个问题被证明是无解的. 

TCP就是这样采用方案1，没收到ack就重传，直到timeout. 

### 拜占庭将军问题

更general的问题: 一些节点会behave maliciously , 比如会恶意背叛. 

Theorem: 需要3f + 1个节点才能满足f个Byzantine faults. 

### Systems models

这个总结很精辟. 
- Two generals problem: a model of networks
- Byzantine generals problem: a model of node behaviour

而现实系统中，node和network都会出现故障.

考虑三个方面
- network behaviour 
- node behaviour 
- timing behaviour

**network behaviour**

- reliable links: 不会丢message
- fair-loss links: message可能会丢，重复，乱序. 但是不断重发，有一个message最终会get through
- arbitrary: 存在恶意攻击者，干扰甚至篡改message.

network partition: 一部分links断了. 

之间转换：
- fair-loss links + retry + dedup -> reliable links
- arbitrary links + TLS -> fair-loss links

**node behaviour**
- crash-stop (fail-stop): crash后就永远宕机. 比如地震后机器全毁了.
- crash-recovery (fail-recovery): crash后失去in-memory state. 但是之后可以resume. 
- byzantine (fail-arbitrary): 恶意节点

**synchrony(timing) assumptions**

- synchronous: latency有上限. 节点执行速度一定.
- asynchronous: latency无上限. 节点可能突然停止执行. 
- partially synchronous: 一定时间系统asynchronous. 其余时间synchronous. 

这里的"同步" "异步"概念和计算机领域其他地方出现的不太一样.

为何network会产生很高的latency
- congestion 
- route reconfiguration. 比如要求在buffer待很久. 

为何node会偶尔停止执行
- thread scheduling
- stop-the-world gc
- page faults, swap, trashing

确实. 

针对场景选择一个合适的system model很重要. 比如on-prem cluster就不要去考虑arbitrary network和byzantine fault了.

**Comment by jasonliu747** [comment]
给钟哥点赞:thumbsup:

**Comment by vycezhong** [comment]
## Lecture 3: Time, clocks and ordering of events

- physical clocks: count seconds elapsed.  
- logical clocks: count events. 

### Physical time

现在一般用GPS作为物理时间源了. 卫星携带atomic clock，广播时间. 所以datacenter屋顶一般有天线. 

leap second: [闰秒](https://zh.wikipedia.org/wiki/%E9%97%B0%E7%A7%92)，传说中的“+1s”和"-1s". 发生在每年30 June和31 Dec. 现在软件一般都会忽略. 但有时候真会make a difference....

![image](https://user-images.githubusercontent.com/25879526/115571864-f9ff2c80-a2f1-11eb-9861-91c8e5cd9dc6.png)


- Unix time: number of seconds since 1970.1.1 UTC. 不包括leap seconds. 
- ISO 8601: 就是转成年月日时分秒，并且切换时区.

**Comment by vycezhong** [comment]
## Lecture 4: Broadcast protocal and logical time 

### logical time 

logical clock其实就是个counter, designed to capture causal dependencies. i.e.  a -> b => T(a) < T(b)

#### Lamport clocks

![image](https://user-images.githubusercontent.com/25879526/116260318-2828b480-a7a9-11eb-8f1c-a651e58a91bf.png)

- 每个node都有一个counter t
- attach t to messages
- a -> b => L(a) < L(b) 但是反过来不成立. 甚至可能 L(a) = L(b) 但是 a != b

(L(e), N(e))可以uniquely identifies event e. N(e)是指node name顺序. 这样可以定义一个total order. 

缺点:
- L(a) < L(b) 不能分辨 a -> b 还是 a || b (需要vector clocks)

#### Vector clocks

用一个vector而不是scalar才存counter. 

![image](https://user-images.githubusercontent.com/25879526/116263854-552a9680-a7ac-11eb-941a-f439b795c10e.png)

用generalized inequality来确定order. 

properties of this order:
- V(a) < V(b) <=> a -> b
- V(a) = V(b) <=> a = b (the same event)
- V(a) || V(b) <=> a || b

这个不错.

**Comment by vycezhong** [comment]
## Replication

终于要开始fault tolerance话题了. replication算是最widely used的一个方法了.

- replica: a node that has a copy of the data

好处:
- fault tolerance
- load balance 

最大的问题: **consistency** 

举了一个点赞的例子. 非常有意思. 

idempotence: 幂等. f(x) = f(f(x)). 

比如会出现下面这样的inconsistency问题，而且还无法区分是哪种情况，在server看来结果都一样. 
![image](https://user-images.githubusercontent.com/25879526/116282117-f883a780-a7bc-11eb-8d0a-61d5ccfdec63.png)

解决办法: 利用timestamp (得用logical time). 下图中false不是真的remove，而是指暂时invisible，叫tomestone (因为可能其他node收到更新的true消息). tomestone可以之后gc. 这样可以tell哪个消息是更新的. 
![image](https://user-images.githubusercontent.com/25879526/116282287-279a1900-a7bd-11eb-8e20-4aa3ac45c437.png)

然后replicas之间周期性sync，检车所有inconsistencies，以最新的写入为准. 

这里的logical clock用lamport或者vector都可以:
- 使用lamport clock (with total order): 实现的逻辑是last writer wins(LWW). 这有data loss，丢掉了另一个并行发生的写入.
- 使用vector clock (with partial order): 如果t1 || t2 则保存并行发生的写入. 这叫multi-vallue register.

**Comment by vycezhong** [comment]
## Consensus 

最重要的一章. 主要掌握Raft. 

先抛出问题: 如何做fault-tolerance的total order broadcast. 比如，leader-based的实现中，如果leader挂了或者unavailable怎么办? 

manual failover，即人为干预. 人的速度太慢了，需要很长时间才能recovery. 必须要实现automatically choose a new leader. 这就是consensus. 

consensus: 几个node需要对a single value达成共识. 在total order broadcast的context下， 这个value指的是the next message to deliver. 

常见的consensus algorithms:
- Paxos
- Raft

主要看Raft. 

### Raft

**consensus system models**
Paxos, Raft assume a **partially synchronous**, **crash-recovery** system model.

**Comment by vycezhong** [comment]
## Replica consistency 

先给个consistency定义
- ACID: 数据库的一个概念. atomicity, consistency, isolation, durability. 是为了保证transactions的有效性而提出的. 这不是distributed system讨论的概念. 
- Read-after-write consistency. 
- Replication: replica should be "consistent" with other replicas. 对"consistent"概念的不同理解就有了不同的consistency model.

### Two-phase commit 

先看看atomicity in ACID transactions
- atomicity: 一个transaction要么commit要么aborts
- 一旦commit, 这个update是durable
- 一旦aborts, 要没有副作用
- ACID consistency 依赖于atomicity 
- 分布式的ACID, 需要全部commit或者全部abort
- 如果any node crashes, 其他node全部要abort

但这和consensus不太一样. 具体对比如下:
![image](https://user-images.githubusercontent.com/25879526/116406105-e8260800-a862-11eb-96fa-00e08716c90a.png)

一般实现atomicity in ACID是通过two-phase commit (2PC)
![image](https://user-images.githubusercontent.com/25879526/116406588-684c6d80-a863-11eb-903d-b80e27c8c728.png)

如果coordinator crashes. 
- coordinator把决定写入到disk
- 恢复的时候读取decision然后发送到replicas. (或者abort如果在crash前未写入)

problem: 如果coordinator在prepare后broadcasting decision之前挂了，那么replicas会一直block直到coordinator recovers. 

solution: 用total order broadcast

**Comment by vycezhong** [comment]
## Concurrency control in applications

### collaboration software

比如google docs. 每个用户其实都有一个local replica. 可以update local replica anytime(甚至offline). sync with others when network available.

algorithms:
- Conflict-free replicated data types (CRDTs)
- Operational Transformation (OT)

不是很感兴趣. 没看算法细节.

### Google Spanner 

集大成之作

a data system with millions of nodes, petabytes of data, distributed across datacenters worldwide. 

consistency properties:
- serializable transaction isolation
- linearizable reads and writes
- many shards. atomic commit of transactions across shards.

使用的techniques:
- State machine replication (Paxos) within a shard
- two-phase locking for serializability
- two-phase commit for cross-shard atomicity 
 
有趣的点: read-only transactions require **no locks**. 

MVCC: multi-version concurrency control 
![image](https://user-images.githubusercontent.com/25879526/116503983-f0755600-a8e9-11eb-9c98-fcbdb8b6a003.png)

为了得到commit timestamps. 需要满足causality，即T1 -> T2 => t1 < t2. 本来是用logical clocks来解决这个问题的. 但是linearizability取决于real-time order，logical time是无法反映这一点的(因为可能这两个replica根本不通信, 而logical clock是依赖attach timestamp to message实现的). 

所以他们使用TrueTime来解决...准确的physical time是不知道的. TrueTime是返回一个范围. [T_{earliest}, T_{latest}], 真实的physical timestamp在这范围之内. 这个范围大小是uncertainty. 每次commit的时候，需要等待uncertainty时间. 这能保证real time dependency. 

TrueTime实现是每个datacenter装一个原子钟或者GPS接收器.....每30s同步一次时间. 

![image](https://user-images.githubusercontent.com/25879526/116504829-d6d50e00-a8eb-11eb-879b-7a8cde20a33c.png)

可以看到其实平均uncertainty很短，也就4ms左右，这远低于cross-continent级别的latency (~100ms).

**Comment by vycezhong** [comment]
不知不觉看完了....斗胆评价一下. 

感觉这门课更新手友好一些，适合我这样的小白. 单独讲某个技术是没有意思的，这门课把技术产生的context讲清楚了.

这个表很重要. 

|Problem | Must wait for communication | Requires synchrony | 
|----| ---- | ---- | 
| atomic commit | all participating nodes | partially synchronous |
| consensus, total order broadcast, linearizable CAS| quorum |partially synchronous | 
|linearizable get/set| quorum | asynchronous | 
|eventual consistency, causal broadcast, FIFO broadcast | local replica only | asynchronous | 

最后一个是AP. 因为牺牲了强一致性但保证可用性，但也不是完全抛弃了一致性，等到通信恢复了，还是可以sync实现最终一致性，长远来看数据还是一致的.
